server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inno
    hikari:
      username: postgres
      password: postgres
      schema: items
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  task:
    scheduling:
      pool:
        size: 1

schedulers:
  scan-task: "-"

core:
  numbers-blocking-enabled: false
  blocked-numbers:
    - "1"
    - "2"
    - "3"
    - "4"

integrations:
  executor:
    client:
      url: "http://localhost:8031/executor"
      connect-timeout: 1s
      read-timeout: 30s
    product:
      url: "http://localhost:8083"
      connect-timeout: 1s
      read-timeout: 30s